# Generated by Django 3.2.12 on 2022-03-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=300)),
                ('is_merged', models.BooleanField(default=True)),
            ],
        ),
    ]
